### PR TITLE
Update Main.java

### PR DESCRIPTION
**Pull request by Durga12371**
change print block

### CODE REVIEW

**Comment by saisrisangita** [comment]
ok

**Review by saisrisagita — APPROVED** [review]

**Review by Tidu9991 — APPROVED** [review]

**Review by saisrisagita — APPROVED** [review]
perfect

**Comment by Durga12371** [comment]
please review it

**Comment by Durga12371** [comment]
i changed print block

**Review by Tidu9991 — APPROVED** [review]

**Pull request closed without merging**
